spring:
  datasource:
    url: jdbc:mysql://localhost:3306/aspis?serverTimezone=UTC&characterEncoding=UTF-8
    username: root
    password: mysqlpassword
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update  # create, create-drop, update, validate, none 중 선택
    show-sql: true  # 콘솔에서 SQL 쿼리 출력
    properties:
      hibernate:
        format_sql: true  # SQL 문을 보기 좋게 출력
        dialect: org.hibernate.dialect.MySQL8Dialect
        jdbc:
          time_zone: UTC

  # (선택) 데이터 초기화 스크립트 사용
  sql:
    init:
      mode: always  # always, never, embedded (내장 DB에서만 실행)

# (선택) 로깅 레벨 설정
logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type.descriptor.sql: trace
